apiVersion: v1
kind: Pod
metadata:
  name: fullapp-pod
spec:
  containers:
    - name: fullapp-pod
      image: busybox
      command:
        - sh
        - -c
        - |
          echo "APP ENV: $APP_ENV"
          echo "APP PORT: $APP_PORT"
          echo "APP COLOR: $APP_COLOR"
          echo "MAX CONNECTIONS: $MAX_CONNECTIONS"
          echo "DB USER: $DB_USER"
          echo "DB NAME: $DB_NAME"
          sleep 3600
      envFrom:
        - secretRef:
            name: db-secret
      envFrom:
        - configMapRef:
            name: app-config
  restartPolicy: Never